# Actividad 1.1. Introducción a Estructuras de Datos

## Temas a cubrir
- Listas (list)
- Diccionarios (dict)
- Arrays (Numpy)
- DataFrames (Pandas)

**Importante:** Revisar los datos antes de ejecutar el modelo.

**Tip:** Usa `pandas` para limpiar datos rapidamente.

In [2]:
# Verificar que los paquetes funcionan
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

# Ejemplo básico de estructuras de datos
lista = [1, 2, 3, 4, 5]
diccionario = {"nombre": "Juan", "edad": 25}
array = np.array([1, 2, 3, 4, 5])
dataframe = pd.DataFrame({"columna1": [1, 2, 3], "columna2": [4, 5, 6]})

print("Lista:", lista)
print("Diccionario:", diccionario)
print("Array NumPy:", array)
print("DataFrame Pandas:")
print(dataframe)

NumPy version: 2.4.3
Pandas version: 3.0.1
Lista: [1, 2, 3, 4, 5]
Diccionario: {'nombre': 'Juan', 'edad': 25}
Array NumPy: [1 2 3 4 5]
DataFrame Pandas:
   columna1  columna2
0         1         4
1         2         5
2         3         6


## Lista multidimensional   

In [3]:
# Crear una lista multidimensional con NumPy

import numpy as np

# Crear un array 2D (matriz 3x3)
matriz_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print("Matriz 2D (3x3):")
print(matriz_2d)
print(f"Forma: {matriz_2d.shape}")
print(f"Tipo de datos: {matriz_2d.dtype}")
print()
# imprimir un elemento en particular


# crear un ciclo que imprima cada elemento de la matriz
print("Elementos de la matriz:")    

for i in range(matriz_2d.shape[0]):  # Itera sobre las filas
    for j in range(matriz_2d.shape[1]):  # Itera sobre las columnas
  
        print(f"Elemento en la posición ({i}, {j}):", matriz_2d[i, j])  # Imprime el elemento en la posición (i, j)

       # print(matriz_2d[i, j], end=' ')  # Imprime el elemento seguido de un espacio
    print()  # Imprime una nueva línea después de cada fila     

print("*" * 30)  # Separador visual

# Crear un array 3D (tensor)
tensor_3d = np.array([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10], [11, 12]]])

print("Tensor 3D (3x2x2):")
print(tensor_3d)
print(f"Forma: {tensor_3d.shape}")
print()
print("Elementos del tensor:")
for i in range(tensor_3d.shape[0]):  # Itera sobre la primera dimensión
    for j in range(tensor_3d.shape[1]):  # Itera sobre la segunda dimensión
        for k in range(tensor_3d.shape[2]):  # Itera sobre la tercera dimensión
            print(f"Elemento en la posición ({i}, {j}, {k}):", tensor_3d[i, j, k])  # Imprime el elemento en la posición (i, j, k)

# Crear arrays multidimensionales con funciones de NumPy
zeros_2d = np.zeros((2, 3))  # Matriz de ceros 2x3
ones_3d = np.ones((2, 2, 2))  # Tensor de unos 2x2x2
random_2d = np.random.rand(3, 2)  # Matriz aleatoria 3x2

print("Matriz de ceros (2x3):")
print(zeros_2d)
print()

print("Tensor de unos (2x2x2):")
print(ones_3d)
print()

print("Matriz aleatoria (3x2):")
print(random_2d)

Matriz 2D (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma: (3, 3)
Tipo de datos: int64

Elementos de la matriz:
Elemento en la posición (0, 0): 1
Elemento en la posición (0, 1): 2
Elemento en la posición (0, 2): 3

Elemento en la posición (1, 0): 4
Elemento en la posición (1, 1): 5
Elemento en la posición (1, 2): 6

Elemento en la posición (2, 0): 7
Elemento en la posición (2, 1): 8
Elemento en la posición (2, 2): 9

******************************
Tensor 3D (3x2x2):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Forma: (3, 2, 2)

Elementos del tensor:
Elemento en la posición (0, 0, 0): 1
Elemento en la posición (0, 0, 1): 2
Elemento en la posición (0, 1, 0): 3
Elemento en la posición (0, 1, 1): 4
Elemento en la posición (1, 0, 0): 5
Elemento en la posición (1, 0, 1): 6
Elemento en la posición (1, 1, 0): 7
Elemento en la posición (1, 1, 1): 8
Elemento en la posición (2, 0, 0): 9
Elemento en la posición (2, 0, 1): 10
Elemento en la posición (2, 1, 0): 11
Elemento en la posici

## DataFrames

In [13]:
import pandas as pd

# Crear datos en forma de diccionario
data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro"],
    "Edad": [23, 35, 29, 41],
    "Ciudad": ["Santiago", "Valparaíso", "Concepción", "La Serena"],
    "Puntaje": [85, 90, 78, 92]
}

# Crear el DataFrame
df = pd.DataFrame(data)

# Mostrar el DataFrame
print(df)
# recorrear el dataframe e imprimir cada fila
print("Filas del DataFrame:")   
for index, row in df.iterrows():
    print(f"Fila {index}: Nombre={row['Nombre']}, Edad={row['Edad']}, Ciudad={row['Ciudad']}, Puntaje={row['Puntaje']}")    





  Nombre  Edad      Ciudad  Puntaje
0    Ana    23    Santiago       85
1   Luis    35  Valparaíso       90
2  María    29  Concepción       78
3  Pedro    41   La Serena       92
Filas del DataFrame:
Fila 0: Nombre=Ana, Edad=23, Ciudad=Santiago, Puntaje=85
Fila 1: Nombre=Luis, Edad=35, Ciudad=Valparaíso, Puntaje=90
Fila 2: Nombre=María, Edad=29, Ciudad=Concepción, Puntaje=78
Fila 3: Nombre=Pedro, Edad=41, Ciudad=La Serena, Puntaje=92


In [ ]:
# Crear un DataFrame con valores faltantes
# explicacion por cada linea de codigo  
from sklearn.experimental import enable_iterative_imputer # Habilita la función IterativeImputer, que es una técnica de imputación avanzada para manejar valores faltantes en conjuntos de datos. Esta línea es necesaria para usar IterativeImputer, ya que está en fase experimental en scikit-learn.   
from sklearn.impute import IterativeImputer # Importa la clase IterativeImputer desde el módulo sklearn.impute. Esta clase se utiliza para realizar la imputación de valores faltantes en un conjunto de datos utilizando un enfoque iterativo, donde se modelan las relaciones entre las características para predecir los valores faltantes.
X = pd.DataFrame({ # Crea un DataFrame de pandas llamado 'X' con dos columnas: 'edad' y 'puntaje'. La columna 'edad' contiene algunos valores numéricos y un valor faltante (np.nan), mientras que la columna 'puntaje' contiene valores numéricos sin faltantes. Este DataFrame se utilizará para demostrar cómo manejar los valores faltantes utilizando la clase IterativeImputer.
    'edad': [25, 30, np.nan, 40],
    'puntaje': [85, 90, 78, 92]
})

imputer = IterativeImputer() # Crea una instancia de la clase IterativeImputer. Esta instancia se utilizará para realizar la imputación de los valores faltantes en el DataFrame 'X'. El método IterativeImputer modela las relaciones entre las características para predecir los valores faltantes de manera iterativa.
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns) # Aplica el método fit_transform del imputer al DataFrame 'X' para realizar la imputación de los valores faltantes. El resultado se convierte en un nuevo DataFrame llamado 'X_imputed', que contiene los valores imputados en lugar de los valores faltantes. Las columnas del nuevo DataFrame se mantienen iguales a las del DataFrame original 'X' utilizando el argumento columns=X.columns.
print(X_imputed)

       edad  puntaje
0  25.00000     85.0
1  30.00000     90.0
2  12.76941     78.0
3  40.00000     92.0


# dataframe desde una lista de listas 

In [12]:
data = [
    ["Ana", 23, "Santiago"],
    ["Luis", 35, "Valparaíso"]
]

df = pd.DataFrame(data, columns=["Nombre", "Edad", "Ciudad"])

print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Luis    35  Valparaíso


# dataframe Desde un archivo CSV

In [4]:
df = pd.read_csv("datos_clientes.csv")
df

,nombre,edad,profesion,sueldo_liquido
0,Camila Torres,26,Ingeniero,758040
1,Juan Pérez,39,Abogado,720967
2,Pedro Soto,34,Diseñador,1213089
3,Luis Martínez,37,Abogado,2389629
4,María González,49,Ingeniero,1403482
5,Fernanda Silva,25,Doctor,709478
6,Carla Díaz,33,Vendedor,2247780
7,María González,54,Ingeniero,801905
8,Camila Torres,38,Doctor,1093672
9,Luis Martínez,63,Diseñador,2177939
