# Ciencia de Datos
## desafíos complejos en el procesamiento, análisis y modelado de datos
## recolección, limpieza y transformación de datos hasta el desarrollo, evaluación y despliegue de modelos predictivos en entornos de producción


## obj: orientada a preparar a cada estudiante para integrarse en equipos de ciencia de datos y machine learning con dominio de herramientas como Python, frameworks, librerías especializadas y entornos ad hoc a la ciencia de dat

  # METODOLOGÍA : Aprendizaje basado en proyectos
  ## herramientas modernas como Pandas y NumPy



# Actividad 1.1
## Introducción a estructuras de datos
## Te familiarizarás con la creación, transformación y optimización de estructuras como DataFrames y arrays multidimensionales

## Estas competencias te permitirán ahorrar tiempo y reducir errores en las etapas de modelado.

# DATA SCIENCIE PIPELINE (canalización de ciencia de datos)
## RAW DATA - DATA CLEANING - CLEAN DATA

## Elimina los pasos manuales para reducir errores y permite un análisis escalable y eficiente, que normalmente abarca la adquisición de datos, el preprocesamiento, el análisis exploratorio de datos (EDA), el modelado y la implementación

# 
## Un flujo de datos (data flow) en ciencia de datos es el movimiento, transformación y procesamiento automatizado de datos desde su origen hasta su destino final (como un almacén de datos o modelo de IA). Incluye etapas como captura, limpieza, integración y carga, asegurando que los datos sean utilizables

## Componentes y Características Clave:
## Procesamiento: Puede ser en tiempo real (streaming) para datos inmediatos o por lotes (batch) para grandes volúmenes.
## Orquestación: Gestiona la dependencia y el orden de ejecución de las tareas.
## Objetivo: Transformar datos brutos en información estructurada y reutilizable para el análisis y la toma de decisiones.

# En resumen, es la "tubería" que permite que los datos pasen de fuentes dispersas a convertirse en conocimiento aplicado, vital para el aprendizaje automático y la inteligencia empresarial

# 5 HORAS PEDAGOGICAS Y 2 HRS AUTONOMAS
## Introducción a Estructuras de Datos
# Listas (list) - Diccionarios (dict) - Arrays (Numpy) - DataFrames (Pandas) 


## El análisis de datos es el proceso de explorar, investigar y recopilar información de los datos utilizando medidas y visualizaciones estadísticas.
## El objetivo del análisis de datos es desarrollar una comprensión de los datos al descubrir tendencias, relaciones y patrones. El análisis de datos es tanto una ciencia como un arte. Por un lado, requiere el conocimiento de estadística, técnicas de visualización y paquetes de Python como Numpy, Pandas y Seaborn.

# ¿Qué es el cálculo numérico? Python y Numpy para principiantes

In [ ]:
# Importa la clase IterativeImputer, que es el algoritmo que rellena valores faltantes (NaN)
# Este método usa el algoritmo MICE (Multivariate Imputation by Chained Equations)

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

import pandas as pd
import numpy as np  # Agregar esto si no está arriba

X = pd.DataFrame({
    'edad': [25, 30, np.nan, 45],
    'salario': [30000, np.nan, 45000, 60000],
    'experiencia': [2, 5, 7, np.nan]
})

print(X)
imputer = IterativeImputer(max_iter=10)
X_imputed = imputer.fit_transform(X)

print(X_imputed) # Imprime el DataFrame con los valores faltantes rellenados


   edad  salario  experiencia
0  25.0  30000.0          2.0
1  30.0      NaN          5.0
2   NaN  45000.0          7.0
3  45.0  60000.0          NaN
[[2.50000000e+01 3.00000000e+04 2.00000000e+00]
 [3.00000000e+01 3.89999994e+04 5.00000000e+00]
 [3.46831765e+01 4.50000000e+04 7.00000000e+00]
 [4.50000000e+01 6.00000000e+04 1.20000001e+01]]


In [5]:
import numpy as np

# 1. Crear un arreglo bidimensional (Matriz 2x3)
# 2 filas, 3 columnas
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print("--- Matriz Original (2x3) ---")
print(matriz)

# 2. Acceder a elementos [fila, columna]
print("\nElemento en fila 1, columna 2:", matriz[1, 2]) # Resultado: 6

# 2. Acceder a elementos [fila, columna]
print("\nElemento en fila 1, columna 1:", matriz[1, 1]) # Resultado: 3

# 3. Operaciones aritméticas (vectorizadas)
print("\n--- Matriz multiplicada por 2 ---")
print(matriz * 2)

# 4. Cambiar la forma del arreglo (reshape)
# De 2x3 a 3x2
matriz_redimensionada = matriz.reshape(3, 2)
print("\n--- Matriz redimensionada (3x2) ---")
print(matriz_redimensionada)

# 5. Obtener dimensiones
print("\nForma del arreglo (shape):", matriz.shape) # Resultado: (2, 3)



--- Matriz Original (2x3) ---
[[1 2 3]
 [4 5 6]]

Elemento en fila 1, columna 2: 6

Elemento en fila 1, columna 1: 5

--- Matriz multiplicada por 2 ---
[[ 2  4  6]
 [ 8 10 12]]

--- Matriz redimensionada (3x2) ---
[[1 2]
 [3 4]
 [5 6]]

Forma del arreglo (shape): (2, 3)
